# .mega-linter.yml

REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yml

DEFAULT_BRANCH: main
FILTER_REGEX_EXCLUDE: 'dist/.*'
LINTER_RULES_PATH: .
VALIDATE_ALL_CODEBASE: true

DISABLE_LINTERS:
  - ACTION_ZIZMOR
  - JAVASCRIPT_ES
  - COPYPASTE_JSCPD
  - TYPESCRIPT_ES

DISABLE:
  - JSON

DISABLE_ERRORS_LINTERS:
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
