# See: https://prettier.io/docs/en/configuration
# Prettier configuration for YAML files.
{
  "$schema": "https://www.schemastore.org/prettierrc.json",
  singleAttributePerLine: true,
  singleQuote: false,
  endOfLine: lf,
}
